# Generated by Django 4.0.2 on 2022-02-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='oink',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
