# Generated by Django 4.0.2 on 2022-02-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_oink_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oink',
            name='file',
        ),
    ]
